### ISSUE TITLE
Logo, design og farger og fonter

### ISSUE THREAD

**Issue by eklem** [eklem/stortinget#13]
# logo

Lag en variant av riksløven, gjerne litt håndtegnet, men få den til å ha stramme linjer/skarpe hjørner, selv om de er litt upresise.

# farger

```css
.main {
  color: #702146;
}
.mainLight: {
  color: #B51E6F;
}
.contrast {
  color: #cf0a2c;
}
.background {
  background: #d6cfc7;
}

.background:hover {
  background: #eae6e2;
}
```
